=== Vamshi Basupalli
_Email-id_: vamshi.basupalli@outlook.com + 
_Phone_: +91 86391 75844 +
_Address_: Giridhari Homes Murari, Kismatpur, Hyderabad, TS-500086

==== Summary & Highlights
* Over 15 years of programming and research experience with _Distributed Systems, Software Security, High Performance Computing_ and _Embedded Systems_
* Built scalable web services using _Python asyncio_ and _Kubernetes_, and _Serverless_ 
* Built API client libraries; CLI tools; plugins for _Jenkins_ and build systems such as _maven, gradle_ and _ant_
* Worked extensively on programming for _multi-cores_ and _vectorization/SIMD_ units
* A portable vehicle diagnostic scanner that I significantly contributed towards was featured in Motor magazine’s best tools for the year 2007
* Master of Science (Major: Computer Sciences) with thesis and a few published papers

==== Skill Set

[width="90%",cols="32%,68%",style="literal"]
|==========================
| Languages | Python, JavaScript, Typescript, Bash, Scala, Go, Java, C/C++, HTML5, CSS3
| Web Frameworks | aiohttp, Flask, Tornado, Serverless
| Virtualization | Kubernetes, Helm, Docker, Virtual Machines
| Databases | MongoDB, PostgreSQL, Elasticsearch, SQlite
| CI/CD | Jenkins, TravisCI
| Web Frontend | Bootstrap, Web Sockets, JQuery
| Cloud | AWS (cloudwatch, lightsail, KMS, Route-53, Lambda, SNS, SQS, boto3)
| Message Queues | RabbitMQ, Redis, AWS SQS
| Distributed Systems/High Performance Computing | Message Passing Interface (MPI), OpenMP, Pthreads, Vectorization and Polyhedral Model Techniques
| Build Systems | Maven, Gradle, Ant, Make
| Operating Systems | Linux/Unix, SMX (an Embedded OS), Palm OS
|==========================

==== Work Experience/History
.Principal Software Engineer, Enabledata Technologies (Remote), India. June 2021 – till date
Building the backend for https://itilitihealth.com[Itilil Health]

* Customized _Prior Authorization Check_ application APIs for a customer's public portal.
* Improved the performance of _Prior Authorization Check_ API by over 3 times.
* Built a _Functional Test Suit_ that integrates with https://www.gurock.com/testrail/[Test Rails]
* Built backend for a web-based ETL accelerator tool

**Tools/Technologies**: Node.js, AWS Serverless, AWS DynamoDB, AWS SQS, Python, Scala, Azure Databricks

.Software Engineer - Consulting, IBM, Austin, Tx. Dec 2018 – June 2021
Built the backend of https://www.kyndryl.com/us/en/services/cloud/multicloud-management[multi-cloud management platform]. 

* Lead the development for _health_ and _actions_ applications in MCMP
* Used _aiohttp, Flask-RESTPlus, MongoDB, RabbitMQ, Elasticsearch_ and _Kubernetes_ to develop the RESTful backend micro-services
* Collaborated with senior architects to design the micro-services and database schemas. Designed and developed alternate database schema which improved performance of the MCMS health dashboard by 20 times
* Built _Helm_ charts to deploy the micro-services on to Kubernetes clusters
* Implemented https://github.com/openservicebrokerapi/servicebroker/blob/v2.15/spec.md[Open Service Broker] to support multi-tenancy

**Tools/Technologies**: Python, Kubernetes, MongoDB, RabbitMQ, Elasticsearch, Docker, Bash


.Systems Programmer, University of Wisconsin-Madison, Madison, WI. Feb 2013 – Oct 2018
https://continuousassurance.org[SWAMP] was funded by Department of Homeland Security (DHS). The goal of the project is to make software more secure.

* Technical lead and one of the main back-end developers for SWAMP. Main responsibilities include automating the application of software assessment tools for languages such as _Java, .NET, Python, Ruby, PHP_ and _JavaScript_
* Point of contact to technical partners, commercial, academic and government, both in the areas of developing new tool technologies and applying these technologies in SWAMP
* Integrated 26 different open source and commercial software assessment tools covering various languages, frameworks and capabilities
* Built SWAMP API clients, CLI and plugins for _maven, gradle_ and _ant_ build systems. Co-lead the development of SWAMP plugins for _Jenkins_ and _Eclipse_
* Mentored 10 graduate students in building various tools for SWAMP

**Tools/Technologies**: Python, Docker, Java, MongoDB, Bash, Linux

.Research Associate, Pacific Northwest National Laboratory, Richland, WA. Mar 2012 – Jan 2013
* Worked on developing an HPC framework to scale simulation/modeling software systems
* Evaluated/studied Bio-inspired solutions for problems in Smart Grids

**Tools/Technologies**: C/C++, pThreads, NetLogo, Python, Linux

.Software Engineer, Apolent Corporation, Fort Collins, CO. May 2010 – Dec 2011
* Optimized and vectorized image processing algorithms for a client developing computer-chip-wafer inspection machines

**Tools/Technologies**: C/C++, Intel intrinsic, Polyhedral model techniques, Linux

.Graduate Research Assistant, Colorado State University, Fort Collins, CO, Aug 2009 – May 2010
* Analyzed North American Animal Disease Spread Model (NAADSM) for performance bottlenecks and provided solutions to remove them

**Tools/Technologies**: C/C++, Linux

.Software Engineer, MindTree Ltd, Bangalore, India, Feb 2005 – Jul 2008
* Worked on the development of a portable scanner for vehicle on-board diagnostics and an in-vehicle network sniffer application
* Implemented vehicle communication protocols such as CAN, ISO-9141 and KW-2000
* Developed device drivers, ported and developed system software and GUI for the product
* Developed a _Palm OS_ based application for a sales team of a consumer electronics company

**Tools/Technologies**: Embedded C/C++, SMS

==== Links
* Github: https://github.com/vamshikr
* Google Scholar: https://scholar.google.com/citations?user=EpBEY-MAAAAJ
* Linkedin: https://www.linkedin.com/in/vamshi-basupalli-94969644/

==== Educational Background
* _Master of Science_ in Computer Science, Aug 2008 to Dec 2011, Colorado State University, Fort Collins, CO
* _PG Diploma in Advanced Computing_, Aug 2004 to Jan 2005, Advanced Computing Training School, Centre for Development in Advanced Computing (CDAC), Bangalore, India
* _Bachelor of Technology_ in Computer Science, July 1999 to May 2003, Jawaharlal Nehru Technological University, India

==== Publications
*	Kupsch, J. A., Miller, B., Basupalli, V. and Burger, J. (2017). _From Continuous Integration to Continuous Assurance_.
*	Kupsch, J. A., Heymann, E., Miller, B., and Basupalli, V. (2016). _Bad and good news about using software assurance tools_. Software: Practice and Experience 47 (1), 143-156.
* Yuki, T., Basupalli, V., Gupta, G., Iooss, G., Kim, D., Pathan, T., Srinivasa, P., Zou, Y. and Rajopadhye, S., (2012). _AlphaZ: A System for Analysis, Transformation, and Code Generation in the Polyhedral Equational Model_. Colorado State University, Tech. Rep.
*	Basupalli, V. (2011). _The AlphaZ verifier_. Master’s Thesis, Colorado State University, Fort Collins.
*	Basupalli, V., Yuki, T., Rajopadhye, S.V., Morvan, A., Derrien, S., Quinton, P., Wonnacott, D. (2011). _ompVerify: Polyhedral Analysis for the OpenMP Programmer_. OpenMP in the Petascale Era, 37-53.
