=== Vamshi Basupalli
_Email-id_: vamshi.basupalli@outlook.com +
_Phone_: (970) 372-8572 +
_Address_: 2811 La Frontera Blvd, Apt 1314, Austin, TX-78728

==== Summary & Highlights
*	7 years of software development experience with *Python* echo-system
* Overall 13 years of professional programming experience in *Web Application Development*, *Systems Programming, Software Security, High Performance Computing (HPC)* and *Embedded Systems*
* Developed RESTful web services/applications with _Python Web Frameworks_ such as *aiohttp*, *Flask* and *Tornado*
* Built complex aggregation pipelines with *MongoDB* and *Elasticsearch*
* Worked with orchestration and containerization technologies such as *Kubernetes* and *Docker*
* Developed API clients and command line interfaces for _RESTful Web services_ in Python, Java and Bash
* Developed  services that run on *Amazon Web Services*: _cloudwatch, lightsail, KMS, Route-53, Lambda_ and _SNS_
*	Developed plugins for Jenkins, and build systems such as *maven*, *gradle* and *ant*
*	The portable vehicle diagnostic scanner that I significantly contributed towards was chosen by Motor magazine as one of the _best tools for the year 2007_
*	Master of Science (Major: Computer Science) with a thesis and few published papers

==== Skill Set

[width="90%",cols="32%,68%",style="literal"]
|==========================
| Languages | Python, Java, Bash, C/C++, JavaScript, HTML5, CSS3
| Web Frameworks | aiohttp, Flask-RESTPlus, Flask, Tornado
| Web Frontend | JQuery, Bootstrap, Web Sockets
| Databases | MongoDB, Elasticsearch, PostgreSQL, SQlite
| Cloud | AWS (cloudwatch, lightsail, KMS, Route-53, Lambda, SNS, boto3)
| Message Queues | RabbitMQ, Redis
| Virtualization | Kubernetes, Docker, Virtual Machines
| CI/CD | Jenkins, TravisCI
| Distributed Systems/High Performance Computing | Message Passing Interface (MPI), OpenMP, Pthreads, Vectorization and Polyhedral Model Techniques
| Build Systems | Maven, Gradle, Ant, Make
| Operating Systems | Linux/Unix, SMX (an Embedded OS)
|==========================

==== Work Experience/History

.Senior Software Engineer, IBM, Austin, Tx. Dec 2018 – till date
Working on building an IBM enterprise product for multi-cloud resource management. It is a micro-services based application that uses Kubernetes for container orchestration.

* Technical lead and senior backend developer for *health* part of the product.
* Used aiohttp, Flask-RESTPlus, MongoDB, RabbitMQ, Elasticsearch, Docker and Kubernetes to develop the RESTful backend micro-services
* Worked closely with architects to design the micro-services and database schemas
* Designed and developed alternate database schema which improved performance of the MCMS health dashboard by 20 times

.Systems Programmer, University of Wisconsin-Madison, Madison, WI. Feb 2013 – Oct 2018
SWAMP is funded by Department of Homeland Security (DHS) and is a collaborative effort of Morgridge Institute for Research, Madison; NCSA & University of Illinois, Urbana-Champaign; Indiana University, Bloomington and the University of Wisconsin, Madison

*	Technical lead and one of the main back-end developers for SWAMP. Main responsibilities include automating the application of software assessment tools for languages such as _Java, .NET, Python, Ruby, PHP_ and _JavaScript_
*	Point of contact to technical partners, commercial, academic and government, both in the areas of developing new tool technologies and applying these technologies in SWAMP
*	Added 26 different open source and commercial software assessment tools covering various languages, frameworks and capabilities
*	Co-lead the development of SWAMP API, CLI and plugins for Jenkins and Eclipse
* Mentored 10 graduate students in building various tools for SWAMP


.Research Associate, Pacific Northwest National Laboratory, Richland, WA. Mar 2012 – Jan 2013
*	Worked on developing an HPC framework to scale simulation/modeling software systems
* Evaluated/studied Bio-inspired solutions for problems in Smart Grids

.Software Engineer, Apolent Corporation, Fort Collins, CO. May 2010 – Dec 2011
* Optimized and vectorized image processing algorithms for a client developing computer-chip-wafer inspection machines

.Graduate Research Assistant, Colorado State University, Fort Collins, CO, Aug 2009 – May 2010
*	Analyzed North American Animal Disease Spread Model (NAADSM) for performance bottlenecks and provided solutions to remove them

.Software Engineer, MindTree Ltd, Bangalore, India, Feb 2005 – Jul 2008
-	Worked on the development of a portable scanner for vehicle on-board diagnostics and an in-vehicle network sniffer application
-	Developed a _Palm OS_ based application for a sales team of a consumer electronics company

==== Links
*	Github: https://github.com/vamshikr
*	Google Scholar: https://scholar.google.com/citations?user=EpBEY-MAAAAJ

==== Educational Background
* _Master of Science_ in Computer Science, Aug 2008 to Dec 2011, Colorado State University, Fort Collins, CO
* _PG Diploma in Advanced Computing_, Aug 2004 to Jan 2005, Advanced Computing Training School, Centre for Development in Advanced Computing (CDAC), Bangalore, India
* _Bachelor of Technology_ in Computer Science, July 1999 to May 2003, Jawaharlal Nehru Technological University, India

==== Publications
*	Kupsch, J. A., Miller, B., Basupalli, V. and Burger, J. (2017). _From Continuous Integration to Continuous Assurance_.
*	Kupsch, J. A., Heymann, E., Miller, B., and Basupalli, V. (2016). _Bad and good news about using software assurance tools_. Software: Practice and Experience 47 (1), 143-156.
* Yuki, T., Basupalli, V., Gupta, G., Iooss, G., Kim, D., Pathan, T., Srinivasa, P., Zou, Y. and Rajopadhye, S., (2012). _AlphaZ: A System for Analysis, Transformation, and Code Generation in the Polyhedral Equational Model_. Colorado State University, Tech. Rep.
*	Basupalli, V. (2011). _The AlphaZ verifier_. Master’s Thesis, Colorado State University, Fort Collins.
*	Basupalli, V., Yuki, T., Rajopadhye, S.V., Morvan, A., Derrien, S., Quinton, P., Wonnacott, D. (2011). _ompVerify: Polyhedral Analysis for the OpenMP Programmer_. OpenMP in the Petascale Era, 37-53.

==== Continuing Education
* Neural Networks and Deep Learning, by Andrew Ng on _Coursera_, Nov 2017 - Dec 2017
* Machine Learning, by Andrew Ng on _Coursera_, Aug 2016 - Sep 2016
