=== Vamshi Basupalli
_Email-id_: vamshi_kr@hotmail.com +
_Phone_: (970) 372-8572 +
_Address_: 914 S. Brooks St, Apt 5, Madison, WI-53715

==== Summary & Highlights
*	12 years of programming experience in _Systems Programming, Software Security, High Performance Computing (HPC)_ and _Embedded Systems_
*	One of the main back-end developers of Department of Homeland Security funded https://continuousassurance.org[Software Assurance Marketplace]
* Experience with developing on/with _Containers (Docker)_ and _Virtual Machines_ in cloud-based environments
*	Developed _API clients_ and _command line interfaces_ in Python, Java and Bash
* Good understanding and knowledge on _Software Security_
*	Experience with _Jenkins_ and _Jenkins_ plugin development
*	Experience with _Eclipse_ plugin development
*	Experience with _Amazon Web Services: lightsail, KMS, Route-53, Lambda_ and _SNS_
*	Experience with NoSQL databases such as _MongoDB_
* Contributed to open source _software assessment_ tools such as _bandit_ and _PMD_ with providing bug fixes
*	Experience with programming on multi-cores and SIMD style optimization
*	Developed/Implemented _vehicle communication protocol stack_
*	Worked with embedded systems at a _hardware_ level
* Experience with documentation markup languages such as _Asciidoc_, _Markdown_ and _LaTeX_
*	Experience with build systems such as _maven_, _gradle_, _ant_ and _make_
*	Good understanding and knowledge on source code management systems such as _git_
* Experience with version control hosting services such as _GitHub_ and _Bitbucket_
*	The portable vehicle diagnostic scanner that I significantly contributed towards was chosen by Motor magazine as one of the _best tools for the year 2007_
* Initiated the usage of _extreme programming_ methodologies into a project that I worked on
* Have knowledge on Machine Learning and Deep Learning (via doing online courses)
*	Member of Static Analysis Results Interchange Format (SARIF) technical committee
*	Have 4 publications including one first author publication
*	Master of Science (Major: Computer Science) with a thesis

==== Skill Set
*	_Programming Languages_: Python, Bash, Java, C/C++, JavaScript
*	_Tools/Libraries/Frameworks_: : Docker, MongoDB, AWS (lightsail, KMS, Route-53, Lambda, SNS), Jenkins, Apache Maven, Apache Ant, Apache Gradle, Eclipse plugin development, JQuery, Bootstrap, Flask, Tornado, Web Sockets, NGINX, dotnet core, Message Passing Interface (MPI), OpenMP, Pthreads, Vectorization and Polyhedral Model Techniques
*	_Operating Systems_: Linux/Unix, SMX (Embedded OS)

==== Work Experience/History

.Systems Programmer, Software Assurance Marketplace (SWAMP). Feb 2013 – Oct 2018
-	SWAMP is funded by Department of Homeland Security (DHS) and is a collaborative effort of Morgridge Institute for Research, Madison; NCSA & University of Illinois, Urbana-Champaign; Indiana University, Bloomington and the University of Wisconsin, Madison
-	Technical lead and one of the main back-end developers for SWAMP. Main responsibilities include automating the application of software assessment tools for languages such as _Java, .NET, Python, Ruby, PHP_ and _JavaScript_
-	Point of contact to technical partners, commercial, academic and government, both in the areas of developing new tool technologies and applying these technologies in SWAMP
-	Added 26 different open source and commercial software assessment tools covering various languages, frameworks and capabilities
-	Co-lead development of SWAMP API, CLI and plugins for Jenkins and Eclipse
- Mentored 10 graduate students in building various tools for SWAMP


.Research Associate, Pacific Northwest National Laboratory, Richland, WA. Mar 2012 – Jan 2013
-	Worked on developing an HPC framework to scale simulation/modeling software systems and evaluated/studied Bio-inspired solutions for problems in Smart Grids

.Software Engineer, Apolent Corporation, Fort Collins, CO. May 2010 – Dec 2011
- Optimized and vectorized image processing algorithms for a client developing computer-chip-wafer inspection machines

.Graduate Research Assistant, Colorado State University, Fort Collins, CO, Aug 2009 – May 2010
-	Analyzed North American Animal Disease Spread Model (NAADSM) for performance bottlenecks and provided solutions to remove them.
-	Thesis: AlphaZ verifier

.Graduate Teaching Assistant, Colorado State University, Fort Collins, CO, Aug 2008 – Dec 2008
- Conducted recitations and lab sessions for _C++_ programming and _Operating Systems_ classes

.Software Engineer, MindTree Ltd, Bangalore, India, Feb 2005 – Jul 2008
-	Worked on the development of a portable scanner for vehicle on-board diagnostics and an in-vehicle network sniffer application
-	Developed a _Palm OS_ based application for a sales team of a consumer electronics company


==== Projects

.Java Integration to SWAMP (UW-Madison, Feb 2013 - Oct 2018)
Added _Java_ software assessment support to SWAMP. Java software that use build systems such as _Apache Ant, Apache Maven, Gradle_ can be automatically assessed with various tools such as _Checkstyle, PMD, SpotBugs, error-prone, OWASP Dependency Check, Parasoft Jtest_ and _Sonatype Application Health Check_ +
*Technologies/Environment:* Python, Java, Ant, Maven, Gradle, Linux

.Dotnet Integration to SWAMP (UW-Madison, Jan 2018 - Oct 2018)
Added _.NET core_ software assessment support to SWAMP. _.NET core_ software that use _MSBuild_ for build systems can be automatically assessed with tools such as _Security Code Scan, Code Cracker_  and _Devskim_ +
*Technologies/Environment:* Python, .NET core, MSBuild, Linux

.Python, Javascript, Ruby, PHP Integration in SWAMP (UW-Madison, Apr 2015 - Oct 2018)
Added _Python, Javascript, Ruby, PHP_ software assessment support to SWAMP. Tools such as  _Bandit, Flake8, Pylint, ESLint, Flow, JSHint, Brakeman, Dawnscanner, Reek, RuboCop, ruby-lint, PHP CodeSniffer_ and _PMPMD_ can be automatically applied to software written in _Python, Javascript, Ruby_ and _PHP_ +
*Technologies/Environment:* Python, Ruby, Linux

.SWAMP Java CLI (UW-Madison, May 2016 - Oct 2018)
The SWAMP Java CLI is a _Java library_ and a _command line interface_ that provides many common operations to a SWAMP instance such as create/upload software packages (versions), configure/start an assessment, check the status of an assessment, and download SCARF results. The Java library is used by SWAMP _Jenkins_ and _Eclipse_ plugins +
*Technologies/Environment:* Java, Eclipse

.SWAMP Python CLI (UW-Madison, Aug 2016 - Oct 2018)
The Python API and CLI for SWAMP, like the _SWAMP Java CLI_ +
*Technologies/Environment:* Python

.SWAMP Jenkins plugin  (UW-Madison, Dec 2016 - Oct 2018)
Co-Developed a  _Jenkins_ plug-in that allows Jenkins projects to use SWAMP to perform static code assessments on their code +
*Technologies/Environment:* Jenkins, Java

.SWAMP blueJ plugin (UW-Madison, Mar 2014 - Apr 2014)
Developed a _blueJ_ IDE plug-in to perform static code assessments in SWAMP +
*Technologies/Environment:* Java

.SCARF viewer (UW-Madison, Mar 2016 - Apr 2016)
Developed a web based application to display SWAMP Common Assessment Results Format (SCARF) results. The SCARF results are displayed in a tabular format along side the source code. +
*Technologies/Environment:* Python, Javascript, Flask, MongoDB, Prism and jQuery.

.GitHub to SWAMP (UW-Madison, Nov 2016 - Nov 2016)
Developed a AWS Lambda function to upload and assess software on GitHub in SWAMP. The assessment get triggered for _push_ or _commit_ events on GitHub+
*Technologies/Environment:* AWS Lambda, AWS SNS, Python

.CodeDx verification (UW-Madison, Sep 2015 - Sep 2015)
A set of programs to start a https://codedx.com/[CodeDx] viewer instance in a linux based virtual machine, upload SCARF results, download results from the CodeDx viewer +
*Technologies/Environment:* Bash

.HPC framework for Electric Grids (PNNL, Mar 2012 - Jan 2013)
Developed a HPC framework to scale simulation/modeling of electric grid software systems +
*Technologies/Environment:* C/C++, MPI, Pthreads

.Bio-Inspired solutions (PNNL, Mar 2012 - Sep 2012)
Evaluated/studied Bio-Inspired solutions for problems in Smart Grids +
*Technologies/Environment:* NetLogo

.Optimizing image processing algorithms (Apolent Corp, May 2010 - Dec 2011)
Used advanced techniques such as _Polyhedral Model_ and _Vectorization_ to optimize the performance of image processing algorithms for a client developing computer chip wafer inspection machines +
*Technologies/Environment:* C/C++, SIMD intrinsics, Polyhedral Model

.AlphaZ verifier (Colorado State University, Jun 2010 - May 2011)
A tool that is part of _AlphaZ_, a research compiler framework based on _Polyhedral Model_. The AlphaZ verifier validates the legality of optimizing transformations for a given computation. The same AlphaZ verifier is used as the back-end engine for ompVerify, a static analysis tool to detect incorrect parallelization in _OpenMP_ programs +
*Technologies/Environment:* Java, Polyhedral Model

.Optimizing  North American Animal Disease Spread Model (Colorado State University, Aug 2009 - May 2010)
Analyzed North American Animal Disease Spread Model (NAADSM) software for performance hot-spots and provided solutions to remove the performance bottlenecks. Additionally, did a coarse grain parallelization of NAADSM using _Granules_, a cloud computing framework +
*Technologies/Environment:* C/C++, Granules, Linux

.In-vehicle network sniffer application (MindTree, Jan 2008 - Jun 2008)
Worked on the development of an in-vehicle network sniffer application. This was on the same platform as the vehicle on-board diagnostics scanner +
*Technologies/Environment:* C/C++, Assembly Languages, Code Warrior, SMX OS, KWP2000, ISO 9141, CAN

.Vehicle on-board diagnostics scanner (MindTree, Aug 2005 - Dec 2007)
Worked on the development of a https://www.snapon.com/diagnostics/us/ethos[portable vehicle on-board diagnostics scanner]. For the scanner, performed hardware debugging, developed device drivers, implemented vehicle communication protocols, ported and developed system software and GUI for the product +
*Technologies/Environment:* C/C++, Assembly Languages, Code Warrior, SMX OS, KWP2000, ISO 9141, CAN

.Palm OS based sales application (MindTree, May 2005 - July 2005)
Developed a _Palm OS_ based application for a sales team of _Godrej_, a consumer electronics company based in India +
*Technologies/Environment:* C, Palm OS, Code Warrior

==== Links
*	Github: https://github.com/vamshikr
*	Google Scholar: https://scholar.google.com/citations?user=EpBEY-MAAAAJ
* Bitbucket: https://bitbucket.org/vamshi_kr

==== Educational Background
* _Master of Science_ in Computer Science, Aug 2008 to Dec 2011, Colorado State University, Fort Collins, CO
* _PG Diploma in Advanced Computing_, Aug 2004 to Jan 2005, Advanced Computing Training School, Centre for Development in Advanced Computing (CDAC), Bangalore, India
* _Bachelor of Technology_ in Computer Science, July 1999 to May 2003, Jawaharlal Nehru Technological University, India

==== Publications
*	Kupsch, J. A., Miller, B., Basupalli, V. and Burger, J. (2017). _From Continuous Integration to Continuous Assurance_.
*	Kupsch, J. A., Heymann, E., Miller, B., and Basupalli, V. (2016). _Bad and good news about using software assurance tools_. Software: Practice and Experience 47 (1), 143-156.
* Yuki, T., Basupalli, V., Gupta, G., Iooss, G., Kim, D., Pathan, T., Srinivasa, P., Zou, Y. and Rajopadhye, S., (2012). _AlphaZ: A System for Analysis, Transformation, and Code Generation in the Polyhedral Equational Model_. Colorado State University, Tech. Rep.
*	Basupalli, V. (2011). _The AlphaZ verifier_. Master’s Thesis, Colorado State University, Fort Collins.
*	Basupalli, V., Yuki, T., Rajopadhye, S.V., Morvan, A., Derrien, S., Quinton, P., Wonnacott, D. (2011). _ompVerify: Polyhedral Analysis for the OpenMP Programmer_. OpenMP in the Petascale Era, 37-53.

==== Continuing Education
* Neural Networks and Deep Learning, by Andrew Ng. Nov 2017
* Machine Learning, by Andrew Ng. Aug 2016 - Sep 2016
